[package]
name = "sdev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr = "1"
gix-url = "0"
thiserror = "1"

[dependencies.clap]
version = "4"
default-features = false
features = ["std", "derive", "error-context", "help", "usage"]
